### ISSUE TITLE
Package hardcoded to only work on Node <7

### ISSUE THREAD

**Issue by CyrusNajmabadi** [yvele/azure-function-express#19]
Hi Yves.  We'd like to use this great package.  However, we're running into a problem due to it having a hard blocker on the version of hte node engine being <7.  Our system works by allowing one to compile with a local version of node (that can effectively be pretty much any version), which then will finally run on Azure (which also supports 8.11.1 and 10.6.0).  

This blocker prevents us from supporting that.  Is there a reason this needs to be in here?  From looking at your code, i can't see anything in it that is particularly node version specific. 

Would you be willing to remove this upper-bound blocker?  I'd be happy to submit the PR for it if so.

**Comment by yvele** [comment]
I'm only supporting node 6 because at the time Azure Functions was only supporting this version.

I wrote the code based on node 6 source code, with a little reverse engineering.

Actually the code works on node 6 and because it uses internal undocumented node features (specific to node 6), we want to make sure everything is compatible with node 8 and 10.

So the `>=6.11.2` node engine part of the `package.json` isn't arbitrary but reflects the real limit of the project.

We also want to run unit tests on node 6, 8 and 10 altogether, through [.travis.yml](https://github.com/yvele/azure-function-express/blob/77ab66ceeea29edc5bfd7209f8a2614da9e0a949/.travis.yml#L5)

I will first merge https://github.com/yvele/azure-function-express/pull/18 (because it may simplify the code and limit mockups). But I also need first to analyse it a bit.

Then we can work to support node 8 and then node 10 (together with node 6) 👍 

What exact version of node are you actually using?


PS: I also recommend you to locally run your project with the exact same version of node that will be used in production. To avoid compatibility problems and surprises. You may use [nvm](https://github.com/creationix/nvm) to locally switch between node versions.

**Comment by yvele** [comment]
By the way @CyrusNajmabadi `engines nodes >=6.11.2 <7` itself doesn't block you to actually use an out of scope node version. It's purely informative.

https://docs.npmjs.com/files/package.json#engines

> Unless the user has set the `engine-strict` config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

**Comment by CyrusNajmabadi** [comment]
It does end up blocking us when using yarn:

```
error azure-function-express@1.3.0: The engine "node" is incompatible with this module. Expected version ">=6.5.0 <7".
error Found incompatible module
```

**Comment by CyrusNajmabadi** [comment]
> PS: I also recommend you to locally run your project with the exact same version of node that will be used in production. To avoid compatibility problems and surprises. You may use nvm to locally switch between node versions.

We're a library that works with many different versions of node.  We do support the 6, 8 and 10 series :)   That's how we ran into this issue.  I was using your code on v6 and then our test harness broke on this when validating against 8 and 10 :)
